### ISSUE TITLE
Client side error handling missing in signup/update user page

### ISSUE THREAD

**Issue by nmghelani** [prithvi-punjabi/cs546c_group3_resale_finalproject#5]

**Comment by nmghelani** [comment]
- [x] Date (Date must be checked event if type=date is set & also don't allow future dates)
- [x] ZIP code (Same as date)
- [x] State (Just check if it is 2 chars long and only contains letters)
- [x] Phone number (Check if it only numbers with/without dashes)
- [x] Email (Validate email with regex)
- [x] Don't remove spaces from inputs (address/city/biography) - happening on both pages signup & updateuser

**Comment by RishikeshYadav95** [comment]
Added the required client-side validations. Please retest and resolve.

**Comment by nmghelani** [comment]
> Added the required client-side validations. Please retest and resolve.

Signup page is clear. Can you make these changes in user update page too? @RishikeshYadav95

**Comment by RishikeshYadav95** [comment]
I have added them to both pages. Retest and let me know if any of them need fixing.
